# This is a basic workflow to help you get started with Actions

name: manually test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: # 手动触发事件
    inputs: # 需要输入的参数
      name: # 参数名
        description: '输入参数1' # 参数描述信息
        required: true # 是否必须
        default: '默认值1' # 默认值
      home: # 参数名
        description: '输入参数2'
        required: false # 是否必须
        default: '默认值2'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  say_hello: # 任务名称
    runs-on: ubuntu-latest # 运行环境
    steps: # 步骤
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
